INSERT INTO products (slug, name, description, price_cents, image_url, in_stock, category) VALUES
('velvet-red-satin-lipstick', 'Velvet Red Satin Lipstick', 'A true classic red with a satin finish that glides on smoothly. Buildable from a soft wash to full opacity, and comfortable enough to wear all day.', 1800, '/products/velvet-red-satin-lipstick.jpg', 24, 'lipsticks'),
('midnight-berry-matte-lipstick', 'Midnight Berry Matte Lipstick', 'A deep berry matte for evenings out. Long-wearing pigment that stays put through dinner without drying your lips.', 1800, '/products/midnight-berry-matte-lipstick.jpg', 18, 'lipsticks'),
('bare-rose-nude-lipstick', 'Bare Rose Nude Lipstick', 'Your lips but better. A warm rose nude that suits most skin tones and works for the office or a quiet weekend.', 1650, '/products/bare-rose-nude-lipstick.jpg', 30, 'lipsticks'),
('coral-blush-cream-lipstick', 'Coral Blush Cream Lipstick', 'A soft coral with a creamy, hydrating finish. Light enough for everyday and flattering in daylight.', 1650, '/products/coral-blush-cream-lipstick.jpg', 22, 'lipsticks'),
('poppy-red-lip-duo', 'Poppy Red Lip Duo', 'A bright poppy lipstick paired with a matching liquid lacquer. Wear them separately or layer for extra shine.', 2400, '/products/poppy-red-lip-duo.jpg', 12, 'lipsticks'),
('rosewater-shine-lip-gloss', 'Rosewater Shine Lip Gloss', 'A sheer rose gloss with a non-sticky formula. Adds a glassy shine over lipstick or on bare lips.', 1200, '/products/rosewater-shine-lip-gloss.jpg', 35, 'lip-gloss'),
('nude-peach-lip-gloss', 'Nude Peach Lip Gloss', 'A warm peach nude gloss enriched with oat butter for softness. Comfortable enough to reapply all day.', 1200, '/products/nude-peach-lip-gloss.jpg', 28, 'lip-gloss'),
('sugar-plum-gloss-trio', 'Sugar Plum Gloss Trio', 'Three of our best-selling glosses in one set: a red, a pink and a nude. A good way to find your shade.', 3000, '/products/sugar-plum-gloss-trio.jpg', 8, 'lip-gloss'),
('glow-lip-oil', 'Glow Lip Oil', 'A tinted lip oil that treats and colours at once. Softens dry lips overnight or adds a light sheen during the day.', 1500, '/products/glow-lip-oil.jpg', 20, 'lip-care'),
('everyday-beauty-gift-set', 'Everyday Beauty Gift Set', 'A curated set of our everyday favourites, boxed and ready to give. Includes a lipstick, a gloss and a lip oil.', 5500, '/products/everyday-beauty-gift-set.jpg', 6, 'gift-sets');